import { redirect } from 'next/navigation';
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export default async function RoadmapPage() {
  const supabase = await createSupabaseServerClient();
  const { data } = await supabase.auth.getUser();
  if (!data.user) redirect('/login');

  return (
    <main className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8">
      <Card className="border-border/60 bg-card/80">
        <CardHeader>
          <CardTitle>Learning roadmap</CardTitle>
        </CardHeader>
        <CardContent className="grid gap-4 md:grid-cols-2">
          {['Daily plan', 'Weekly plan', 'Monthly plan', 'Projects', 'Courses', 'Books', 'Certifications', 'Interview prep'].map((item) => (
            <div key={item} className="rounded-3xl border border-border/60 bg-background p-4 text-sm text-muted-foreground">
              <p className="font-semibold text-foreground">{item}</p>
              <p className="mt-2">Generated by the roadmap agent after the career match is selected.</p>
            </div>
          ))}
        </CardContent>
      </Card>
    </main>
  );
}