import { redirect } from 'next/navigation';
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export default async function ReportPage() {
  const supabase = await createSupabaseServerClient();
  const { data } = await supabase.auth.getUser();

  if (!data.user) redirect('/login');

  const { data: report } = await supabase.from('analyses').select('*').eq('user_id', data.user.id).order('created_at', { ascending: false }).limit(1).maybeSingle();

  return (
    <main className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8">
      <Card className="border-border/60 bg-card/80">
        <CardHeader>
          <CardTitle>Career report</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-sm leading-7 text-muted-foreground">
          <p>This page renders the latest polished report generated by the report agent.</p>
          <pre className="overflow-auto rounded-3xl bg-muted p-5 text-xs text-foreground">{JSON.stringify(report ?? {}, null, 2)}</pre>
        </CardContent>
      </Card>
    </main>
  );
}